services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: librechat
    # ports:
    #   - 3080:3080
    depends_on:
      - traefik
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.librechat.rule=Host(`librechat.demian.website`)"
        - "traefik.http.routers.librechat.entrypoints=websecure"
        - "traefik.http.routers.librechat.tls=true"
        - "traefik.http.routers.librechat.tls.certresolver=le"
    networks:
      - librechat_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3" 

  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=librechat_default"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=demian85@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - librechat_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3" 

  mongodb:
    image: mongo:8.0.17
    container_name: librechat-mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod
    networks:
      - librechat_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3" 
  
  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: librechat-meilisearch
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    volumes:
      - ./meili_data_v1.12:/meili_data
    networks:
      - librechat_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3" 
  
  vectordb:
    image: pgvector/pgvector:0.8.0-pg15-trixie
    container_name: librechat-vectordb
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - librechat_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3" 
  
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: librechat-rag_api
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
    networks:
      - librechat_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3" 

volumes:
  pgdata2:

networks:
  librechat_default:
    name: librechat_default
  # external network for sharing mongodb
  # shared_network:
  #   external: true